version: "3.8"
services:
  app:
    container_name: quex-app
    build:
      context: ./app
    ports:
      - "80:3000"
      - "9229:9229"
    volumes:
      - /app/node_modules
      - ./app:/app
    depends_on:
      - redis
    environment:
      REDIS_HOST: quex-redis
      REDIS_PORT: 6379
      TWILIO_SEND_MESSAGE_QUEUE: twilio_send_message_queue

  redis:
    image: "redis:alpine"
    container_name: quex-redis
    ports:
      - "6380:6379"